# Configuration of code formatting
[tool.blue]
line-length = 100
target-version = ['py310']
extend-exclude = 'migrations'

[tool.isort]
line_length = 100
profile = 'black'                      # We use blue which is close enough to black.
py_version = 310
extend_skip_glob = ['**/migrations/*']

[tool.pylint.messages_control]
max-line-length = 100

enable = [
  'useless-suppression', # helpful to remove dead lint ignore comments
]

disable = [
  'wildcard-import',            #
  'missing-docstring',          # C0111 missing docstrings are ok
  'missing-function-docstring', # C0116 missing docstrings are ok
  'missing-module-docstring',   # C0114 missing docstrings are ok
  'missing-class-docstring',    # C0115 missing docstrings are ok
  'too-few-public-methods',     # R0903 allow simple data/entity classes etc.
  'unused-wildcard-import',     #
]

ignore = 'migrations' # Do not enforce naming rules for generated files.


[tool.pytest.ini_options]
log_cli = true
log_cli_format = "%(asctime)s %(levelname)s %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_level = "INFO"
log_format = "%(levelname)8s %(message)s"
# log_format = "%(asctime)s %(levelname)8s %(message)s"
# norecursedirs = ['article', 'eat', 'sample_1']
#norecursedirs = ['article', 'sah', 'eat', 'sample_1']
#norecursedirs = ['article', 'tests', 'eat', 'sample1']
markers = [
  "wip: marks tests as work-in-progress (deselect with '-m \"not wip\"')",
  "wipz: marks tests as unfinished work-in-progesz (deselect with '-m \"not wipz\"')",
  "todo: marks tests as unfinished (deselect with '-m \"not todo\"')",
  "ok: marks tests as tested ok (deselect with '-m \"not ok\"')",
  "order: marks ordering for tests (example)",
]
# testpaths = ['tests', 'article', 'conftest_glue', 'eat', 'sah']
testpaths = ['tests', 'sah', 'conftest_glue', 'article']
pythonpath = ['tests', 'sah', 'conftest_glue', 'article']
# bdd_features_base_dir = 'sah'

addopts = '--ignore=temp' # Don't look for py files in temp folder
